import os

os.environ['PYTHONDONTWRITEBYTECODE'] = '1'  # Rule 1: Disable pycache

#!/usr/bin/env python3
"""
Database Schema Auto-Maintenance System
========================================

Automatically exports and versions database schema after changes.
Ensures documentation stays synchronized with actual database structure.

Following Rule 2: All data in database (schema versions tracked)
Following Rule 4: LLM self-management (autonomous schema maintenance)
"""

import os

os.environ['PYTHONDONTWRITEBYTECODE'] = '1'

import logging
import sqlite3
from datetime import datetime
from typing import Dict, List, Optional

from database_interface import DatabaseInterface, resolve_db_path

logger = logging.getLogger(__name__)

class SchemaAutoMaintenance:
    """Automatic database schema export and versioning."""

    SCHEMA_FILE_PATH = "complete_database_schema.sql"

    def __init__(self, db_path: Optional[str] = None):
        db_path = resolve_db_path(db_path)
        self.db = DatabaseInterface(db_path)
        self.db_path = db_path
        self._ensure_schema_versions_table()
        self._ensure_schema_file_exists()

    def _ensure_schema_versions_table(self):
        """Create schema_versions table if it doesn't exist."""
        self.db.execute_query("""
            CREATE TABLE IF NOT EXISTS schema_versions (
                version_id INTEGER PRIMARY KEY AUTOINCREMENT,
                version_number TEXT NOT NULL,
                applied_at TEXT NOT NULL,
                changes_summary TEXT,
                table_count INTEGER,
                total_columns INTEGER,
                schema_hash TEXT
            )
        """)
        logger.info("Schema versions table initialized")

    def _ensure_schema_file_exists(self):
        """Auto-create complete_database_schema.sql if it doesn't exist.

        Per Master Ruleset: Database Schema Auto-Update System should auto-create
        the schema file with a fresh database schema dump if not found.
        """
        if not os.path.exists(self.SCHEMA_FILE_PATH):
            logger.info(f"Schema file '{self.SCHEMA_FILE_PATH}' not found - creating fresh dump")
            success = self.regenerate_schema_file(self.SCHEMA_FILE_PATH)
            if success:
                logger.info(f"[OK] Auto-created '{self.SCHEMA_FILE_PATH}' with current database schema")
            else:
                logger.error(f"[FAIL] Failed to auto-create '{self.SCHEMA_FILE_PATH}'")
        else:
            logger.debug(f"Schema file '{self.SCHEMA_FILE_PATH}' exists")

    def export_current_schema(self) -> str:
        """Export current database schema as SQL."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Get all table creation statements
        cursor.execute("""
            SELECT sql FROM sqlite_master
            WHERE type='table' AND name NOT LIKE 'sqlite_%'
            ORDER BY name
        """)

        schema_lines = []
        schema_lines.append("-- Database Schema Export")
        schema_lines.append(f"-- Generated: {datetime.now().isoformat()}")
        schema_lines.append("-- Auto-generated by schema_auto_maintenance.py")
        schema_lines.append("")

        for row in cursor.fetchall():
            if row[0]:  # Some tables might have NULL sql
                schema_lines.append(row[0] + ";")
                schema_lines.append("")

        # Get all index creation statements
        cursor.execute("""
            SELECT sql FROM sqlite_master
            WHERE type='index' AND name NOT LIKE 'sqlite_%'
            ORDER BY name
        """)

        indexes = cursor.fetchall()
        if indexes:
            schema_lines.append("-- Indexes")
            for row in indexes:
                if row[0]:
                    schema_lines.append(row[0] + ";")
                    schema_lines.append("")

        conn.close()
        return "\n".join(schema_lines)

    def get_schema_stats(self) -> Dict:
        """Get statistics about current schema."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Count tables
        cursor.execute("""
            SELECT COUNT(*) FROM sqlite_master
            WHERE type='table' AND name NOT LIKE 'sqlite_%'
        """)
        table_count = cursor.fetchone()[0]

        # Count total columns across all tables
        cursor.execute("""
            SELECT name FROM sqlite_master
            WHERE type='table' AND name NOT LIKE 'sqlite_%'
        """)

        total_columns = 0
        for (table_name,) in cursor.fetchall():
            cursor.execute(f"PRAGMA table_info({table_name})")
            total_columns += len(cursor.fetchall())

        conn.close()

        return {
            'table_count': table_count,
            'total_columns': total_columns
        }

    def detect_schema_changes(self) -> Optional[List[str]]:
        """Detect changes from last recorded version."""
        # Check if schema_versions table exists
        try:
            last_version = self.db.execute_query("""
                SELECT table_count, total_columns
                FROM schema_versions
                ORDER BY version_id DESC
                LIMIT 1
            """)
        except Exception:
            # Table doesn't exist or is empty - this is first run
            return ["Initial schema version"]

        if not last_version:
            return ["Initial schema version"]

        current_stats = self.get_schema_stats()
        last_stats = last_version[0]

        changes = []
        if current_stats['table_count'] != last_stats['table_count']:
            diff = current_stats['table_count'] - last_stats['table_count']
            changes.append(f"Tables: {last_stats['table_count']} → {current_stats['table_count']} ({diff:+d})")

        if current_stats['total_columns'] != last_stats['total_columns']:
            diff = current_stats['total_columns'] - last_stats['total_columns']
            changes.append(f"Columns: {last_stats['total_columns']} → {current_stats['total_columns']} ({diff:+d})")

        return changes if changes else None

    def regenerate_schema_file(self, output_path: str = None) -> bool:
        """Regenerate schema file and log version.

        Args:
            output_path: Path to write schema file. Defaults to SCHEMA_FILE_PATH.
        """
        if output_path is None:
            output_path = self.SCHEMA_FILE_PATH

        try:
            # Export schema
            schema_sql = self.export_current_schema()

            # Write to file
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(schema_sql)

            # Get stats
            stats = self.get_schema_stats()

            # Detect changes
            changes = self.detect_schema_changes()
            changes_summary = "; ".join(changes) if changes else "No changes detected"

            # Generate version number
            version_number = datetime.now().strftime("v%Y%m%d_%H%M%S")

            # Log version
            self.log_schema_version(
                version_number=version_number,
                changes_summary=changes_summary,
                table_count=stats['table_count'],
                total_columns=stats['total_columns']
            )

            logger.info(f"Schema exported to {output_path} - {changes_summary}")
            return True

        except Exception as e:
            logger.error(f"Failed to regenerate schema file: {e}")
            return False

    def log_schema_version(self, version_number: str, changes_summary: str,
                          table_count: int, total_columns: int):
        """Log a new schema version."""
        self.db.execute_query("""
            INSERT INTO schema_versions
            (version_number, applied_at, changes_summary, table_count, total_columns)
            VALUES (?, ?, ?, ?, ?)
        """, (version_number, datetime.now().isoformat(), changes_summary,
              table_count, total_columns))

        logger.info(f"Logged schema version {version_number}")

    def get_version_history(self, limit: int = 10) -> List[Dict]:
        """Get recent schema version history."""
        return self.db.execute_query("""
            SELECT version_number, applied_at, changes_summary,
                   table_count, total_columns
            FROM schema_versions
            ORDER BY version_id DESC
            LIMIT ?
        """, (limit,))

if __name__ == "__main__":
    # Run schema export
    maintenance = SchemaAutoMaintenance()

    print("=" * 70)
    print("DATABASE SCHEMA AUTO-MAINTENANCE")
    print("=" * 70)

    # Export schema
    success = maintenance.regenerate_schema_file()

    if success:
        print("\n[OK] Schema exported successfully")

        # Show version history
        history = maintenance.get_version_history(limit=5)
        if history:
            print("\nRecent Schema Versions:")
            for v in history:
                print(f"  {v['version_number']}: {v['changes_summary']}")
                print(f"    Tables: {v['table_count']}, Columns: {v['total_columns']}")
    else:
        print("\n[FAIL] Schema export failed")
